#ifndef PIUBTN_DRV_DEFS_H
#define PIUBTN_DRV_DEFS_H

#define PIUBTN_DRV_VID			0x0D2F
#define PIUBTN_DRV_PID		    0x1010

#define PIUBTN_DRV_CONFIG  0x01
#define PIUBTN_DRV_IFACE   0x00

#define PIUBTN_DRV_USB_CTRL_TYPE_IN 	0xC0
#define PIUBTN_DRV_USB_CTRL_TYPE_OUT	0x40
#define PIUBTN_DRV_USB_CTRL_REQUEST	0xAE
#define PIUBTN_DRV_USB_REQ_TIMEOUT	10000

#define PIUBTN_DRV_BUFFER_SIZE 8

#endif