#ifndef ASSET_GAME_VERSION_H
#define ASSET_GAME_VERSION_H

/* Note: Version IDs must be sync with server code */
enum asset_game_version {
  ASSET_GAME_VERSION_INVALID = 0,
  ASSET_GAME_VERSION_FIRST = 1,
  ASSET_GAME_VERSION_SECOND = 2,
  ASSET_GAME_VERSION_OBG = 3,
  ASSET_GAME_VERSION_OBG_SE = 4,
  ASSET_GAME_VERSION_THE_COLLECTION = 5,
  ASSET_GAME_VERSION_PERFECT_COLLECTION = 6,
  ASSET_GAME_VERSION_EXTRA = 7,
  ASSET_GAME_VERSION_PREMIERE_1 = 8,
  ASSET_GAME_VERSION_PREX_1 = 9,
  ASSET_GAME_VERSION_REBIRTH = 10,
  ASSET_GAME_VERSION_PREMIERE_2 = 11,
  ASSET_GAME_VERSION_PREX_2 = 12,
  ASSET_GAME_VERSION_PREMIERE_3 = 13,
  ASSET_GAME_VERSION_PREX_3 = 14,
  ASSET_GAME_VERSION_EXCEED = 15,
  ASSET_GAME_VERSION_EXCEED_2 = 16,
  ASSET_GAME_VERSION_ZERO = 17,
  ASSET_GAME_VERSION_NX = 18,
  ASSET_GAME_VERSION_PRO = 19,
  ASSET_GAME_VERSION_NX2 = 20,
  ASSET_GAME_VERSION_NXA = 21,
  ASSET_GAME_VERSION_FIESTA = 22,
  ASSET_GAME_VERSION_PRO2 = 23,
  ASSET_GAME_VERSION_FIESTA_EX = 24,
  ASSET_GAME_VERSION_FIESTA_2 = 25,
  ASSET_GAME_VERSION_INFINITY = 26,
  ASSET_GAME_VERSION_PRIME = 27,
  ASSET_GAME_VERSION_PRIME_2 = 28,
  ASSET_GAME_VERSION_XX = 29
};

#endif
