#ifndef PIUIO_DRV_DEFS_H
#define PIUIO_DRV_DEFS_H

#define PIUIO_DRV_VID			0x0547
#define PIUIO_DRV_PID		    0x1002

#define PIUIO_DRV_CONFIG  0x01
#define PIUIO_DRV_IFACE   0x00

#define PIUIO_DRV_USB_CTRL_TYPE_IN 	0xC0
#define PIUIO_DRV_USB_CTRL_TYPE_OUT	0x40
#define PIUIO_DRV_USB_CTRL_REQUEST	0xAE
#define PIUIO_DRV_USB_REQ_TIMEOUT	10000

#define PIUIO_DRV_BUFFER_SIZE 8

#endif